# Generated by Django 4.2.6 on 2023-10-12 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartmecanico', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ['-deleted_at', '-updated_at', 'year', 'brand', 'plate'], 'verbose_name': 'Veículo', 'verbose_name_plural': 'Veículos'},
        ),
    ]
