# Generated by Django 4.2.6 on 2023-10-12 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartmecanico', '0002_alter_vehicle_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Justificativa para o cancelamento'),
        ),
    ]
