# Generated by Django 4.2.6 on 2023-10-12 00:37

from django.db import migrations, models
import employee_management.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de Exclusão')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('bio', models.TextField(blank=True, max_length=500, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=employee_management.models.get_file_path)),
                ('cep', models.CharField(max_length=10, verbose_name='CEP')),
                ('logradouro', models.CharField(max_length=255, verbose_name='Logradouro')),
                ('complemento', models.CharField(blank=True, max_length=255, null=True, verbose_name='Complemento')),
                ('bairro', models.CharField(max_length=255, verbose_name='Bairro')),
                ('localidade', models.CharField(max_length=255, verbose_name='Cidade')),
                ('uf', models.CharField(max_length=2, verbose_name='Estado')),
                ('employee_type', models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], default='PF', max_length=2)),
                ('cpf', models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='CPF')),
                ('rg', models.CharField(blank=True, max_length=9, null=True, unique=True, verbose_name='RG')),
                ('estado_civil', models.CharField(blank=True, choices=[('solteiro', 'Solteiro'), ('casado', 'Casado'), ('divorciado', 'Divorciado'), ('viuvo', 'Viúvo'), ('separado', 'Separado Judicialmente')], max_length=20, null=True)),
                ('genero', models.CharField(blank=True, choices=[('masculino', 'Masculino'), ('feminino', 'Feminino'), ('nao_binario', 'Não-binário'), ('trans_masculino', 'Trans Masculino'), ('trans_feminino', 'Trans Feminino'), ('agenero', 'Agênero'), ('genero_fluido', 'Gênero Fluido'), ('two_spirit', 'Two-Spirit'), ('homem_cis', 'Homem Cis'), ('mulher_cis', 'Mulher Cis'), ('nao_informar', 'Prefiro não informar'), ('outro', 'Outro')], max_length=20, null=True)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_admissao', models.DateField(blank=True, null=True)),
                ('cnpj', models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='CNPJ')),
                ('razao_social', models.CharField(max_length=200, verbose_name='Razão Social')),
                ('nome_fantasia', models.CharField(max_length=200, verbose_name='Nome Fantasia')),
                ('inscricao_estadual', models.CharField(blank=True, max_length=20, null=True)),
                ('inscricao_municipal', models.CharField(blank=True, max_length=20, null=True)),
                ('ramo_atividade', models.CharField(blank=True, max_length=255, null=True)),
                ('numero_funcionarios', models.PositiveIntegerField(blank=True, null=True, verbose_name='Qtd Funcionários')),
                ('representante_legal', models.CharField(blank=True, max_length=255, null=True)),
                ('data_fundacao', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Recurso Humano',
                'verbose_name_plural': 'Recursos Humano',
            },
        ),
    ]
