# Generated by Django 4.2.5 on 2023-09-18 13:56

import appointment.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('address', '0001_initial'),
        ('vehicle', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de Exclusão')),
                ('hour', models.CharField(help_text='Formato: 00:00', max_length=5, verbose_name='Hora do Serviço')),
                ('day', models.DateField(help_text='Formato: YYYY-MM-DD', verbose_name='Data do Serviço')),
                ('protocol', models.CharField(default=appointment.models.generate_protocol, max_length=22, unique=True, verbose_name='Protocolo')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Appointment', related_query_name='schedule', to='address.address', verbose_name='Endereço')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee_management.employeeinfo', verbose_name='Mecânico')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Appointment', related_query_name='schedule', to='services.service', verbose_name='Serviço')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Appointment', related_query_name='schedule', to='vehicle.vehicle', verbose_name='Veículo')),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
            },
        ),
    ]
