# Generated by Django 4.2.5 on 2023-09-18 13:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ultima Atualização')),
                ('deleted_at', models.DateTimeField(null=True, verbose_name='Data de Exclusão')),
                ('brand', models.CharField(max_length=255, verbose_name='Marca Veículo')),
                ('model', models.CharField(max_length=255, verbose_name='Modelo Veículo')),
                ('fuel', models.CharField(max_length=255, verbose_name='Combustível')),
                ('year', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(code='invalid_year', message='O ano de fabricação deve estar no formato YYYY', regex='^[0-9]{4}$')], verbose_name='Ano Fabricação')),
                ('odometer', models.CharField(max_length=6, verbose_name='Hodômetro')),
                ('plate', models.CharField(db_index=True, max_length=7, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_plate', message='Placa deve estar no formato ABC1234 ou ABC1D23', regex='^[A-Z]{3}[0-9]{4}$|^[A-Z]{3}[0-9][A-Z][0-9]{2}$')], verbose_name='Placa do Veículo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
            },
        ),
    ]
