# Generated by Django 4.2.6 on 2023-10-13 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_history', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmenthistory',
            name='event_type',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointmenthistory',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
